### ISSUE TITLE
Unable to retrieve elements from WebView

### ISSUE THREAD

**Issue by AliceCarroll239** [appium/appium-desktop#1126]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Unable to retrieve elements from WebView
You can see the comparison of 1.13 and 1.15.0-1 versions on the screenshots

## Environment

- I am running Appium Desktop version 1.15.0-1
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux
![115 appium](https://user-images.githubusercontent.com/29251216/66698641-45418380-ece8-11e9-8303-fa4e999cc055.png)
![113 appium](https://user-images.githubusercontent.com/29251216/66698644-48d50a80-ece8-11e9-99bc-8b80025819dc.png)

**Comment by dpgraham** [comment]
Try setting `automationName=UiAutomator1` in your caps. If that doesn't work, then unfortunately there won't be any resolution for this because we can't control what elements the Android testing frameworks report to Appium.

I would also recommend for webviews that you should be using a web context instead of using native components.
