### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Error in building: Ill-formed XML document (multiple root elements detected). Try changing the 'normalizeTagNames' driver setting to 'true' in order to workaround the problem.

### ISSUE THREAD

**Issue by Mahen27** [appium/appium-desktop#1154]
Getting below error when i try to run automation on 2 emulators.

Error:
An unknown server-side error occurred while processing the command. Original error: Error in building: Ill-formed XML document (multiple root elements detected). Try changing the 'normalizeTagNames' driver setting to 'true' in order to workaround the problem.

I have attached the appium server logs for reference. Please help me to understand about this issue

**Comment by Mahen27** [comment]
Attaching the server logs
[appium-server-logs copy.txt](https://github.com/appium/appium-desktop/files/3772374/appium-server-logs.copy.txt)

**Comment by Mahen27** [comment]
Facing the above problem in MAC , Using below appium version

Version 1.15.1 (1.15.1.20191013.2)

**Comment by KazuCocoa** [comment]
It means your app's generated XML by Android framework has characters that are not valid for XML parser. `normalizeTagNames` potentially can fix the issue replacing such invalid characters.

The `normalizeTagNames` is https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/settings.md . How to use it as caps is `Update settings` section in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

**Comment by KazuCocoa** [comment]
Close not AD issue.
(If the error remains after applying the `normalizeTagNames`, please consider creating issue on appium-repo. https://github.com/appium/appium

**Comment by mykola-mokhnach** [comment]
I saw similar errors happening if one tries to execute parallel driver sessions without providing appropriate capabilities

**Comment by Mahen27** [comment]
> I saw similar errors happening if one tries to execute parallel driver sessions without providing appropriate capabilities

Yes still i am facing the same issue when i try to run in multiple emulators in parallel, same script is working fine without any issues in emulator. Need some suggesstions

**Comment by KazuCocoa** [comment]
1. Try `UiAutomator2` as the deprecation message in the log
    > [warn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m   DEPRECATION WARNING:
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The 'automationName' capability was not provided in the desired 
[warn] [35m[Appium][39m   capabilities for this Android session
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   Setting 'automationName=UiAutomator2' by default and using the 
[warn] [35m[Appium][39m   UiAutomator2 Driver
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The next major version of Appium (2.x) will **require** the 
[warn] [35m[Appium][39m   'automationName' capability to be set for all sessions on all 
[warn] [35m[Appium][39m   platforms
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   In previous versions (Appium <= 1.13.x), the default was 
[warn] [35m[Appium][39m   'automationName=UiAutomator1'
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   If you wish to use that automation instead of UiAutomator2, please 
[warn] [35m[Appium][39m   add 'automationName=UiAutomator1' to your desired capabilities
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   For more information about drivers, please visit 
[warn] [35m[Appium][39m   http://appium.io/docs/en/about-appium/intro/ and explore the 
[warn] [35m[Appium][39m   'Drivers' menu
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
2. Set `systemPort` http://appium.io/docs/en/advanced-concepts/parallel-tests/ properly

**Comment by mmbug** [comment]
@mykola-mokhnach why you always close issues that are not solved are you lazy or crazy?

**Comment by jlipps** [comment]
@mmbug we have a workflow for triaging and dealing with issues which @mykola-mokhnach follows. insulting him is not only against our code of conduct but will not make anyone more likely to help in any case.
