### ISSUE TITLE
Interactions Are Not Available For This Element On IOS Appium

### ISSUE THREAD

**Issue by dragon11111** [appium/appium-desktop#1168]
## The problem

On IOS Appium when trying to inspect element, the window shows "interactions are not available for this element", when I was trying to click "Tap" that button on the window but it did not work. Could you please help me on this?

## Environment

Appium version : v.1.15.1
Desktop OS/version used to run Appium: macOS Mojava Version 10.14.4
Node.js version (unless using Appium.app|exe): v10.16.3
Npm or Yarn package manager: 6.11.3
Mobile platform/version under test: IOS 11.4.1
Real device or emulator/simulator: Real device iphone 7
Appium CLI or Appium.app|exe: Appium desktop

Thank you so much!

**Comment by Mbachacou** [comment]
Hello,

Did you have any answers to this problem?

Thanks in advance.

**Comment by KazuCocoa** [comment]
You can try out via script directly instead of Appium Desktop's GUI actions.
I mean _find_element_ the element => click it in JS/Python/Ruby etc.
If the click action did not work by it, Appium cannot do such actions for it. (Expected behaviour as Appium)

If the element area had overwrapped other elements, AD cannot interact with them well.

**Comment by Mbachacou** [comment]
Hello,

Ok thank you but I am already using a script to interact with my application. 

But before being able to do it via a script, I will manually search for the xpaths I need and for that it is very convenient to interact via appium desktop to test if the xpaths work.

Does it mean that the interaction functionality on appium desktop has been removed and will no longer be possible?

**Comment by KazuCocoa** [comment]
> Does it mean...

No.
I forgot the details for now, but Appium checks 'enable', 'clickable'? or some attributes to enable/disable tap/send_key action button on the GUI. So, it depends on your elements, but it potentially could happen other hidden elements on your app overlap your target element. 
(We have not removed/changed the check/interaction logic for a while.)

**Comment by LightStein** [comment]
In my case, not only click but also visibilityOfElementLocated fails, only option I've left is to use getLoaction and TouchAction to tap on element Like:
`new TouchAction(driver).tap(PointOption.point(driver.findElement(element).getLocation()))
.perform();`

**Comment by rolikachamyal** [comment]
Provide more detail of this.. As in my case when there is interaction not available  we can open. a tree structure in appium inspector , as the specific element will not interact but there will be that specific element path that will interact . provide more information or screenshot

**Comment by T61Z8T3** [comment]
![image](https://user-images.githubusercontent.com/78351604/146525701-c9fe62f5-d2e6-4a95-a05e-2051dcea80f4.png)

I have the same issue, only one part in the screen (payment information) is not clickable at all. In the real device or emulator it is fine. By tapping the element for the first time nothing happens and for the second time, the error in the picture is displayed. (.... Do not exist in DOM).
Do you think is it because the element area had overwrapped other elements?

**Comment by rolikachamyal** [comment]
You can try by creating your own xpath if not tried,  or might be developer might have set some criteria  like disabled something and other thing please make sure that xcode version that developer are using  you are working on the same or  does the library they are using support lower version of xcode

**Comment by MakhmudovYakhyo** [comment]
Hello,
What can cause this problem and is there any solution for this?
![image](https://user-images.githubusercontent.com/109512781/203774430-64a62967-7717-43af-947b-165d1df19eba.png)

**Comment by jlipps** [comment]
the inspector has moved to another repo.
