### ISSUE TITLE
1.15.1 crashes Appium with Xcode 11.3 when running tests on Catalina

### ISSUE THREAD

**Issue by yadavsvmx** [appium/appium-desktop#1198]
## The problem

1.15.1 crashes Appium with Xcode 11.3 when running tests on Catalina

## Environment

* Appium version (or git revision) that exhibits the issue:  1.15.1 (1.15.1.20191013.2)
* Last Appium version that did not exhibit the issue (if applicable): 1.13
* Desktop OS/version used to run Appium: 1.15.1 (1.15.1.20191013.2)
* Node.js version (unless using Appium.app|exe):NA
* Npm or Yarn package manager:NA
* Mobile platform/version under test: IOS 12.1
* Real device or emulator/simulator: Real Device

## Link to Appium logs
https://gist.github.com/yadavsvmx/f326d84486c0a045ce2a63dd27a885cb
<script src="https://gist.github.com/yadavsvmx/f326d84486c0a045ce2a63dd27a885cb.js"></script>

## Code To Reproduce Issue [ Good To Have ]

Install Appium 1.15.1
Run the tests using Xcode 11.3 for building the web driver

**Comment by imurchie** [comment]
1. Please try the latest beta of Appium, as much has been done in the way of work on iOS 13+

2. What is happening in the Appium logs?

**Comment by KazuCocoa** [comment]
thanks.
I tried to reproduce this, but i could not yet

**Comment by yadavsvmx** [comment]
This issue happens only on Hybrid apps.

Thanks,
Yadav

**Comment by KazuCocoa** [comment]
I could not replicate with a hybrid app.
Maybe it has a condition to reproduce.

**Comment by kajal-chauhan09** [comment]
When trying to launch WebDriverAgent on Mojave(10.14.5) with Xcode 11.3 and Appium 1.15.1, through Appium it is not launching but installation launching is done through Xcode 11.3 with iOS 13+ version devices.Even if with the Catalina(10.15.3) having the issue with Xcode and Appium latest version could not able to launch driver.

I have updated all npm and node dependencies even if all have executed successfully in my MAC system still getting this issue. 

Can you please suggest asps. 

Have a look on logs:
MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by KazuCocoa** [comment]
What was the output of `carthage bootstrap --platform iOS,tvOS`?

**Comment by omughrabi** [comment]
I am facing the same issue as above and when running the above command `carthage bootstrap --platform iOS,tvOS` I am getting the following result:
`λ ~/ carthage bootstrap --platform iOS,tvOS
*** No Cartfile.resolved found, updating dependencies
Failed to read file or folder at /Users/omar/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/omar/Cartfile, NSUnderlyingError=0x7fa947639d60 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

**Comment by KazuCocoa** [comment]
Did you run the command in appium-webdriveragent module?

**Comment by KazuCocoa** [comment]
1.20 beta dropped carthage
