### ISSUE TITLE
No way to open inspector?

### ISSUE THREAD

**Issue by fasmer** [appium/appium-desktop#142]
## Appium or Appium Desktop?
- [*] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I see the documentation for the app inspector in the ReadMe, but I don't see any way to do this in 1.6.4. Is this an upcoming feature or am I missing something?

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [*] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dem0n0cracy** [comment]
I, too, found the ReadMe confusing. Steps to setup.

1. Click Start Server v1.6.4
2. You'll see 'The server is running' with two Buttons 'Start New Session' and 'Stop Server'
3. Click 'Start New Session'
4. A white screen should appear with four tabs at the top - stay on Automatic Server, under it there should be a Desired Capabilities tab that is selected. Here, you add all the desired capabilities that you currently use in your Automation. (I got them out of my TestRoot.java file)
5. Enter them one by one into screen. 
![fillingindesiredcaps](https://cloud.githubusercontent.com/assets/5766824/25020404/2c88c5a2-205c-11e7-9efd-d1e53a527799.png)
6. Save as... your capabilities.
7. Click Start Session - this for me launches WDA, then launches my App, and it also launches the inspector. The loading icon is a spinning blue and white four pronged circle. Use app as you want and click Refresh to see the objects. 

Any questions?

**Comment by fasmer** [comment]
Yeah I have a question...is this a late April fool's joke? It used to be just one click of a button. The other way I found (not in the documentation) was to manually input the session ID into the Attach to Session tab and launch from there.

**Comment by dem0n0cracy** [comment]
I mean...not having had desktop working since 1.5.3, I'm not complaining. This is a brand new project though and we should be thankful. Once you save your setup, it's just a couple of clicks, but I agree the UI in general needs to be improved.

Where did you get the session-id btw? I know there's another feature request to default to just the one if only one session is running.

**Comment by fasmer** [comment]
After you've started a session and have the app running it generates a session ID in the Appium logs. you just copy/paste that into the Attach to Session area

**Comment by jlipps** [comment]
> is this a late April fool's joke

No, this is not a joke. We opted to reimagine the interface from the old app. One of the big problems with the old app is that desired capabilities were masked by dozens of UI controls which users thought they needed to check or not check, and custom capabilities were very hard to add. So we have designed this interface to allow complete flexibility of capabilities. Yes, it currently means you need to know about desired capabilities, and which ones to add in order to start your session. This is the same thing you need to know to run an appium script in general.

Maybe there are capability "recipes" we could add that would make it easy to get a set of capabilities that works from scratch, so people who don't know what capabilities are necessary will have an easier go of it.

@dem0n0cracy anything you think we could change in the README to make it less confusing?

**Comment by dem0n0cracy** [comment]
I guess I just didn't realize I had to do steps 6 and 7 to open the inspector. It's been a while since 1.4.3 and now I feel dumb for not putting the capabilities in first of all. Also, the recipe idea is good, or maybe a link to the appium site that shows what's available.

**Comment by jcyrss** [comment]
I'm also totally confused by that.
