### ISSUE TITLE
Appium startup error

### ISSUE THREAD

**Issue by xiaohuimc** [appium/appium-desktop#1431]
## The problem

Startup error, please help me.

## Environment

- I am running Appium Desktop version  1.17.1-1
- I am on (pick one):
    - [x] Mac 10.15.5 (19F96)
            Xcod Version 11.5 (11E608c)

## Error

an unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2020-06-16 04:11:02.784 xcodebuild[42027:1114084] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.5-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphoneos13.5-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fcd5d607ba0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** 2020-06-16 04:11:02.799 xcodebuild[42027:1114032] [MT] IDETestOperationsObserverDebug: (BF448A24-0F26-4E47-8A4C-60CCB6EBEF96) Beginning test session WebDriverAgentRunner-BF448A24-0F26-4E47-8A4C-60CCB6EBEF96 at 2020-06-16 04:11:02.800 with Xcode 11E608c on target 📱<DVTiOSDevice (0x7fcd5f7d8050), iPhone, iPhone, 12.4 (16G77), 3c7717ed34e92771e99a92faf416768b63bfe785> { deviceSerialNumber: DNPQQ8RQGRY7 identifier: 3c7717ed34e92771e99a92faf416768b63bfe785 deviceClass: iPhone deviceName: iPhone deviceIdentifier: 3c7717ed34e92771e99a92faf416768b63bfe785 productVersion: 12.4 buildVersion: 16G77 deviceSoftwareVersion: 12.4 (16G77) deviceArchitecture: arm64 deviceTotalCapacity: 11896176640 deviceAvailableCapacity: 10620751872 deviceIsTransient: NO ignored: NO deviceIsBusy: NO deviceIsPaired: YES deviceIsActivated: YES deviceActivationState: Activated isPasscodeLocked: NO deviceType: <DVTDeviceType:0x7fcd602d3eb0 Xcode.DeviceType.iPhone> supportedDeviceFamilies: ( 1 ) applications: (null) provisioningProfiles: (null) hasInternalSupport: NO hasWritableSystem: NO isSupportedOS: YES bootArgs: (null) nextBootArgs: (null) connected: YES isWirelessEnabled: NO connectionType: direct hostname: (null) bonjourServiceName: 6c:72:e7:6c:49:8a@fe80::6e72:e7ff:fe6c:498a._apple-mobdev2._tcp.local. activeProxiedDevice: (null) } (12.4 (16G77)) 2020-06-16 04:11:02.803 xcodebuild[42027:1114085] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.06.16_04-11-01--0700.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-181357F4-AB0B-44A1-9BFD-E60415612F0F/WebDriverAgentRunner-D87787BA-B7CF-4EFB-9211-96259E958D2E/Session-WebDriverAgentRunner-2020-06-16_041102-xsbUYf.log 2020-06-16 04:11:02.967 xcodebuild[42027:1114032] [MT] IDETestOperationsObserverDebug: (BF448A24-0F26-4E47-8A4C-60CCB6EBEF96) Finished requesting crash reports. Continuing with testing. *** If you believe this error represents a bug, please attach the result bundle at /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.06.16_04-11-01--0700.xcresult 2020-06-16 04:11:02.980 xcodebuild[42027:1114032] [MT] IDETestOperationsObserverDebug: 0.185 elapsed -- Testing started completed. 2020-06-16 04:11:02.980 xcodebuild[42027:1114032] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2020-06-16 04:11:02.981 xcodebuild[42027:1114032] [MT]

**Comment by KazuCocoa** [comment]
Perhaps macOS 10.15? has been restricted the write permission in AppiumDesktop.app , so Appium cannot create necessary files in the appium module.
As a workaround, maybe https://github.com/appium/appium-desktop#connect-to-local-appium-server may help

**Comment by arhanechka** [comment]
Facing the same issue. Have you found the way to solve it?
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 xcodebuild error message: 2020-06-25 10:42:17.093 xcodebuild[63173:5775936] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.5-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users//Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/WebDriverAgentRunner_iphoneos13.5-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7feb5e723180 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner. Reason: Cannot test target “WebDriverAgentRunner” on “”: iPhone’s iOS 13.5.1 doesn’t match WebDriverAgentRunner’s iOS 13.15 deployment target.. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by arhanechka** [comment]
I can run WDA by xcode and xcodeBuild^ but can not by appium

**Comment by krischik** [comment]
> Perhaps macOS 10.15? has been restricted the write permission in AppiumDesktop.app , so Appium cannot create necessary files in the appium module.

So Appium is still not ready to work gracefully with the current version of macOS and is in need of workarounds.

**Comment by KazuCocoa** [comment]
Appium dropped Carthage dependencies, so writing permission issue in AppiumDesktop.app in iOS might not occur.
