### ISSUE TITLE
Inspector very slow and often incomplete

### ISSUE THREAD

**Issue by WilfulTravesty** [appium/appium-desktop#1513]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Trying to use inspector in 1.18.0-1 with a real device is very, very slow, and often results in an incomplete XML tree missing most of the screen elements. A screen that took 3-4 seconds to load in a prior release now takes up to 25 seconds to load.

## Environment

- I am running Appium Desktop version 1.18.0-1.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

Example screen capture of an iPhone app, with all the elements missing, replaced with just a single element <XCUIELementTypeOther>:

![ScreenClip](https://user-images.githubusercontent.com/6433968/89810570-e4026080-db02-11ea-8060-b2505cdffa3b.png)

**Comment by KazuCocoa** [comment]
Generating XML(and XPath stuff) is generally slow since Apple does not provide such data.
Appium recursively gets view data by XCTest framework and build the XML with resolving attributes such as visibility.

Potentially, you can set `snapshotMaxDepth` as small value to limit the tree size.
https://appium.io/docs/en/advanced-concepts/settings/

`boundElementsByIndex` via settings API ( https://github.com/appium/appium/blob/862c36bf3749d0f83d3ea6453e936e5a820c5126/CHANGELOG.md#ios-xcuitest ) could help for the tree's element completion.

**Comment by KazuCocoa** [comment]
Possible options are the above comment for now
