### ISSUE TITLE
[Feature request] Ability to automatically start Appium on system start

### ISSUE THREAD

**Issue by sebnil** [appium/appium-desktop#1534]
## Appium or Appium Desktop?

- [ X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium desktop is for us always running on a build server. When the build server has to reboot for system updates, I would like the Appium server to start automatically and be ready to receive commands.

## Environment

- I am running Appium Desktop version _1.18.0-1_.
- I am on (pick one):
    - [ ] Mac
    - [X ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Is the usage not enough with Appium CLI via npm?

**Comment by sebnil** [comment]
I suppose that is a good workaround. But I rather have Appium without dealing with the CLI.

**Comment by sebnil** [comment]
You know, I have been thinking. Appium CLI via npm is good enough. I prefer to use Appium desktop, but I will use Appium CLI instead. Feel free to close the case unless you think this feature should be added.

Thanks for making great software!

**Comment by KazuCocoa** [comment]
Thanks :)

AD is designed to be a viewer of Appium CLI. (then, just pack appium cli as electron app as a quick trial)
Thus, we'd recommend users to use Appium as on CI/build server like your usage.

Probably we only can add a configuration to launch appium server since next launching time, but the launching arguments might be limited. (e.g. cannot set launching argument as command line argument for AD)
