### ISSUE TITLE
Appium 1.18.0-2 and Xcode 12 failure when running ./Scripts/bootstrap.sh

### ISSUE THREAD

**Issue by santtyamen** [appium/appium-desktop#1567]
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I'm trying to run my test on Xcode 12 but I get a Carthage failure when running ./Scripts/bootstrap.sh

[debug] [WebDriverAgent] *** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
[debug] [WebDriverAgent] Build Failed
[debug] [WebDriverAgent] 	Task failed with exit code 1:
[carthage-xcodebuild.TYyo9w.log](https://github.com/appium/appium-desktop/files/5256685/carthage-xcodebuild.TYyo9w.log)

[debug] [WebDriverAgent] 	/usr/bin/xcrun lipo -create

## Environment

- I am running Appium Desktop version 1.18.0-2 
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by anhmainvg** [comment]
I have the same issue when using the **Appium Desktop 1.18.0-2**

as far as I understand, there is report issue with the running carthage to build WebDriverAgent [14611](https://github.com/appium/appium/issues/14611) , and there is already a [workaround solution](https://github.com/appium/WebDriverAgent/pull/373) for this and merged to the beta version [1.19.0-beta.0](https://www.npmjs.com/package/appium/v/1.19.0-beta.0)  because I'm using this beta version now without problems of building the app

Can anyone confirm my comments above? And how to use the Appium Desktop on Xcode 12 now please or waiting for the new Appium Desktop release? @KazuCocoa @mykola-mokhnach 
Many thanks

**Comment by Cuphoria** [comment]
just use some success wda to replace `/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent` or install the appium by npm dont use desktop

**Comment by anhmainvg** [comment]
Thanks, @Cuphoria for the idea. 

@santtyamen I replaced the [bootstrap.sh](https://github.com/appium/WebDriverAgent/tree/master/Scripts) and add the carthage-wrapper.sh and I can run the script

**Comment by KazuCocoa** [comment]
AD can attach to local appium server as https://github.com/appium/appium-desktop#connect-to-local-appium-server
AD will bundle Appium 1.18.2 or 3 (probably 3)

**Comment by DvorahC** [comment]
Hi, I am having the same issue and I stil can't fix anything...
I need to run Appium Desktop in order to use the inspector ( to create automated UI test for iOS).
Here is my configuration:

Xcode 12
Appium Desktop 18
Mac Os 0.15.6
iphone 7 - version iOS 14

When I want to install the WebDriverAgentRunner on the real device I get the same issue all the time after running in my appium-webdriveragent: 

mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d

**Error message:**
Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
	Task failed with exit code 1:
[carthage-xcodebuild.uJMJEC.log](https://github.com/appium/appium-desktop/files/5268520/carthage-xcodebuild.uJMJEC.log)

Then I am stuck and I cannot create the WebDriverAgent on my phone.

I would appreciate some advice,
thanks a lot!
Dvorah

**Comment by KazuCocoa** [comment]
As https://github.com/appium/appium-desktop/issues/1567#issuecomment-697203264 , you can try out Appium 1.18.2 which have Xcode 12 build workaround.
Probably we'll push 1.18.3 with more Xcode 12 build fixes. Then, AD also bump the internal Appium version to 1.18.3.

**Comment by DvorahC** [comment]
> As [#1567 (comment)](https://github.com/appium/appium-desktop/issues/1567#issuecomment-697203264) , you can try out Appium 1.18.2 which have Xcode 12 build workaround.
> Probably we'll push 1.18.3 with more Xcode 12 build fixes. Then, AD also bump the internal Appium version to 1.18.3.

@KazuCocoa ok Thanks for the quick reply, I will try right now and update then. thanks.

**Comment by santtyamen** [comment]
> Thanks, @Cuphoria for the idea.
> 
> @santtyamen I replaced the [bootstrap.sh](https://github.com/appium/WebDriverAgent/tree/master/Scripts) and add the carthage-wrapper.sh and I can run the script

Ok tanks, I downloaded Xcode 11.7 and updated the command line tools whit this version of Xcode

**Comment by BijjamSuresh** [comment]
@KazuCocoa -- Didn't see the 1.18.2 version in the Appium.io site. Latest one is 1.18.0 -2 . Is it the same your stating. Thanks.

**Comment by DaNiELChIoRo** [comment]
I find a kind of ultimate solucion (without having to )... in order to use the lastest WDA you will have to modify the package.json located in the /Applications/Appium.app/Contents/Resources/app/node_modules/appium path (MacOS) to something like this: "appium-xcuitest-driver": "^3.30.0". Then run the command rm -rf node_modules/ && npm i in order to remove the old packages and install the new version. cd node_modules/appium-webdriveragent and do the basic configs (follow the instructions at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md). You might have to restart your GUI Server but it works!.

**Comment by DaNiELChIoRo** [comment]
Forgot to tell but you will have to change the target device families on xcode project if you willing to use it for TVOS. Something like this
<img width="988" alt="Captura de Pantalla 2020-10-01 a la(s) 13 21 24" src="https://user-images.githubusercontent.com/39627096/94848037-04ef7f80-03e9-11eb-899b-ff1515223d2f.png">

**Comment by KazuCocoa** [comment]
> Didn't see the 1.18.2 version in the Appium.io site. Latest one is 1.18.0 -2 . Is it the same your stating. Thanks.

What do you mean?
Appium 1.18.2 is in https://github.com/appium/appium/releases
Appium Desktop does not have the version yet, so we guide https://github.com/appium/appium-desktop#connect-to-local-appium-server to use local appium server. Appium Desktop is just an inspector.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-desktop/releases/tag/v1.18.2

**Comment by IgnacioYanjari** [comment]
@KazuCocoa Hi! The release with number v1.18.2 for Appium desktop have this issue resolved?. Because as u said the version that will have the build fixes will be the number v1.18.3
