### ISSUE TITLE
Not able to launch Android emulator

### ISSUE THREAD

**Issue by Nischalapp** [appium/appium-desktop#167]
I need to use both capabilities to launch Emulator

**avd EmulatorName for ex - Andorid7.1
deviceName  Andorid7.1 ( Same Emulator Name )**

Then it launches Emulator otherwise if i use only this **avd EmulatorName for ex - Andorid7.1 then it gives error saying adb not found device .

## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Please link to a gist of:

1. The appium desktop logs which show the error
2. The appium logs which show this successfully working with appium CLI

**Comment by Nischalapp** [comment]
https://gist.github.com/Nischalapp/1ca4f570197eabc25ba67643224f6e08

My gist link for logs

**Comment by jlipps** [comment]
And where are the appium logs of this working successfully with appium CLI?

**Comment by Nischalapp** [comment]
Hi jonathan,

Thanks for so quick and active response . Please check the logs . Added with successful launch of emulator.

**Comment by jlipps** [comment]
The problem appears to be that you think `deviceName` should be the name of the emulator. In fact this is not the case. Device name should be more generic; what type of device? For example `Android Emulator`. you should put the avd name in the `avd` capability if you want appium to launch it.

But in any case you did not attach logs showing successful test run from appium CLI, so I have no reason to think this problem is related to Appium Desktop, rather than Appium itself. closing here. If you're having trouble getting started, the Appium discuss forums or the Appium issue tracker are the right places. This is for reporting bugs with Appium Desktop that _don't_ reproduce with Appium itself. (That's why we ask those questions in the issue template).

**Comment by Nischalapp** [comment]
Thanks so much.
