### ISSUE TITLE
I use appium desktop and appium cli,Unable to get IOS to IUID？why

### ISSUE THREAD

**Issue by xitele2036** [appium/appium-desktop#1682]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux
![image](https://user-images.githubusercontent.com/15831871/106866977-f27c9f80-6681-11eb-9c85-59dff87a0433.png)

**Comment by xitele2036** [comment]
why show "sessionId" : null

**Comment by KazuCocoa** [comment]
> Unable to get IOS to IUID

No. because of iOS's limitation.

> why show "sessionId" : null

I assume you haven't established a session with a new session request.

**Comment by xitele2036** [comment]
I don't understand what this means? My app webdriveragentruuner can be installed normally, but nothing happens，I use app-inspector haven't got the layer yet

**Comment by KazuCocoa** [comment]
I thought you launched WDA directly via Xcode on a device, and you just opened `http://<IP address>:8100/status` in your browser while You haven't called a new session request via Appium server.
Then, could you share the appium server log as GIST?

Btw, what is app-inspector? It seems non-Appium stuff.

**Comment by xitele2036** [comment]
https://gist.github.com/xitele2036/cac13858d00d85ae8cc3b5e7c88c9c55 
appium server log is here, you see

**Comment by KazuCocoa** [comment]
Thanks, but sorry, I'm a little confusing.

The attached one was only WDA (https://github.com/appium/WebDriverAgent) via Xcode, not Appium server log. I mean logs started from http://appium.io/docs/en/about-appium/getting-started/#starting-appium

appium/WDA is designed to work via https://github.com/appium/appium-xcuitest-driver as XCUITest automation name:
https://dpgraham.github.io/docs/en/drivers/ios-xcuitest/ 
The session should be started by like http://appium.io/docs/en/about-appium/getting-started/?lang=en#session-initialization
Without the call, the `sessionId` should be null.

> I use app-inspector

If you were using different tools, I'd recommend you to ask the app owner or community to ask how to use it rather than here.

**Comment by xitele2036** [comment]
Where can I find a complete, automated build tutorial for appium ios?
The tutorial I found is outdated。。。。。。

**Comment by KazuCocoa** [comment]
oh, sorry. https://dpgraham.github.io/docs/en/drivers/ios-xcuitest/ was wrong.
https://appium.io/docs/en/drivers/ios-xcuitest/ this domain is correct.

https://appium.io/docs/en/about-appium/getting-started/#session-initialization is a basic step to run Appium.
Tweaking automationName etc as https://appium.io/docs/en/drivers/ios-xcuitest/ addresses which capabilities should be modified for iOS.

https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ is for a real device. But iOS singing stuff depends on current Apple's spec. We'd recommend you to learn singing in Apple's resources rather than 3rd party materials basically. Thus, we'd recommend you to try out iOS simulator first to avoid singing things in Apple, first.

Samples or test code could be good resources to check further steps.
https://github.com/appium/appium/tree/master/sample-code
https://github.com/appium/python-client/tree/master/test/functional
https://github.com/appium/ruby_lib_core/blob/master/test/functional

Forum
https://discuss.appium.io/

**Comment by xitele2036** [comment]
Thank you

**Comment by xitele2036** [comment]
Because this is my first contact with the automatically built ios + appium, it is a bit difficult to read the official documents directly, so I can only go to the third-party tutorials

**Comment by KazuCocoa** [comment]
I see.
The difficulties to build iOS stuff for a real device is almost signing stuff. They strongly depend on the Apple environment like Xcode versions, Apple server-side spec related to signing. So it is difficult to maintain step-by-step documentation as 3rd parties like us.
