### ISSUE TITLE
Appium and Appium desktop are not taking the label name as the default accessibility id starting version 1.20+

### ISSUE THREAD

**Issue by JamalMSaad** [appium/appium-desktop#1731]
## The problem

Before release 1.20+ appium or appium desktop was taking the element name as the default accessibility id,for example if we have a button with name "Test" and no accessibility id is defined for it,so  if we use the button name "Test" as the accessibility id , it was working fine in previous appium versions.
Can you please check what was changed in the new versions.

## Environment

- I am running Appium Desktop version 1.20.2.
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment]
I guess XCTest(iOS side) handled the case as `value` internally, not `name` attribute which was used for accessibility id, name and id since Appium 1.20.
Then, you should use `predicate` to detect it as `value`. Please take a look at https://github.com/appium/appium/blob/master/CHANGELOG.md#iosxcuitest
