### ISSUE TITLE
Appium IOS inspector not inspecting elements correspondingly

### ISSUE THREAD

**Issue by vikramaninforce** [appium/appium-desktop#1783]
## The problem
<img width="1100" alt="Screenshot 2021-05-04 at 9 18 59 AM" src="https://user-images.githubusercontent.com/38698652/117486377-2f10ad80-af87-11eb-90de-466fdc22e6f3.png">

Appium IOS inspector not inspecting elements correspondingly. Refer the screenshot attached.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 11.2.2
* Node.js version (unless using Appium.app|exe): v15.12.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Iphone X/14.5
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

**Comment by jlipps** [comment]
Try resizing the issue and waiting a moment. The highlight boxes sometimes take a few moments to appear in the correct position.

**Comment by vikramaninforce** [comment]
@jlipps Its not highlighting the corresponding elements in ios appium locator, though I waited for longtime!

**Comment by jlipps** [comment]
Did you try resizing the window after refreshing the source?

**Comment by KazuCocoa** [comment]
What app did you install?

For now, Appium has two catalog apps for our testing.

https://github.com/appium/ios-uicatalog/tree/master/UICatalog
https://github.com/appium/ios-uicatalog/tree/master/UIKitCatalog

As https://github.com/appium/ios-uicatalog#notice, UIKitCatalog is expected for iOS 13+ since UICatalog hasn't upgrade for safe area etc for newer iOS versions. XCTest framework by Apple does not work expectedly, especially coordinate stuff

(I noticed that potentially https://github.com/appium/appium/blob/master/sample-code/apps/TestApp.app.zip was the old one... Other our tests used the new one tho)

**Comment by vikramaninforce** [comment]
> Did you try resizing the window after refreshing the source?

No change after resizing the window

**Comment by vikramaninforce** [comment]
> What app did you install?
> 
> For now, Appium has two catalog apps for our testing.
> 
> https://github.com/appium/ios-uicatalog/tree/master/UICatalog
> https://github.com/appium/ios-uicatalog/tree/master/UIKitCatalog
> 
> As https://github.com/appium/ios-uicatalog#notice, UIKitCatalog is expected for iOS 13+ since UICatalog hasn't upgrade for safe area etc for newer iOS versions. XCTest framework by Apple does not work expectedly, especially coordinate stuff
> 
> (~I noticed that potentially https://github.com/appium/appium/blob/master/sample-code/apps/TestApp.app.zip was the old one... Other our tests used the new one tho~)

Above screenshot is taken from https://github.com/appium/ios-uicatalog/tree/master/UICatalog app, but same issue is seen in another app which needs to be automated, as I can't share the screen of the prod app, have shared this app.

**Comment by vikramaninforce** [comment]
Actually my test is a ipad app, which always opens in a landscape mode.

**Comment by KazuCocoa** [comment]
>  same issue is seen in another app which needs to be automated,

https://github.com/appium/ios-uicatalog/tree/master/UICatalog hasn't applied iOS's newer layout style such as safe area update. If your app also hasn't applied such updates, XCTest cannot handle it correctly since it seems Apple stop considering them in XCTest. Appium cannot do anything in this case, unfortunately.

I've seen more issues in iPad rather than iPhone. If the wrong coordinate occurred with find_element -> get the element rect, it seems actually XCTest itself returns wrong data. You could report it to Apple.

**Comment by vikramaninforce** [comment]
> > same issue is seen in another app which needs to be automated,
> 
> https://github.com/appium/ios-uicatalog/tree/master/UICatalog hasn't applied iOS's newer layout style such as safe area update. If your app also hasn't applied such updates, XCTest cannot handle it correctly since it seems Apple stop considering them (old style) well in XCTest. Appium cannot do anything in this case, unfortunately.
> 
> I've seen more issues in iPad rather than iPhone. If the wrong coordinate occurred with find_element -> get the element rect, it seems actually XCTest itself returns wrong data. You could report it to Apple.

Understood thanks!
