### ISSUE TITLE
Appium Desktop exe with parameter

### ISSUE THREAD

**Issue by gus484** [appium/appium-desktop#181]
Is it possible to start the appium desktop exe with parameters? I want to run the server immediately with some parameters e.g. logging, without clicking on the start button? Background is to start the appium desktop from python.

I know that i could use node to start the server with the main.js, but is there a way without node installation?

I am running Appium Desktop version 1.0.0 on Windows.

**Comment by dpgraham** [comment]
There's no automatic server startup configuration for Appium Desktop. The only way is to run it from the command line which requires a Node installation. We have discussed making an Appium executable though, it's just not on our roadmap currently.

**Comment by jlipps** [comment]
Yes, appium desktop was designed specifically to _not_ be run programmatically. You can do whatever you want with the CLI version of appium though, including running it as a subprocess.

**Comment by Soumya1987** [comment]
Can you please confirm if there is a way to run Appium Server v1.6.4 (that comes along with Appium Desktop) from Command Prompt for Windows after installation of Node?

**Comment by gus484** [comment]
Yes, I can confirm that. You have to run the main.js file from the appium folder.

For example: "node main.js"

You could also add server parameters .

On my sytem the main.js is found under "C:\Users\USERNAME\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\build\lib"

**Comment by jlipps** [comment]
@Soumya1987 @gus484 I'm really confused why you would want to do this rather than just running Appium CLI itself?

**Comment by Soumya1987** [comment]
@gus484 Thanks for the response. It worked exactly as u had suggested. So, as far as I can understand from this thread, going forward Appium Server can only be started from Command Prompt (besides the Appium Desktop Interface) and cannot be started Programmatically?

**Comment by Soumya1987** [comment]
@jlipps Hello Jonathan, I am a beginner to Appium automation although I have significant experience in Test Automation using other tools. I just watched your video in appium.io and got started with it. I am not sure what you are referring to as Appium CLI. Does Appium CLI stand for Appium Closed Loop Intelligence i.e. Appium desktop??
If that is what you are asking, then I have an answer for you. I am trying to build an automation framework, and my experience tells me that a good framework should have minimal manual interventions. Hence, I was looking for ways to initiate Appium Server Programmatically. But it appears that Appium Desktop does not support that. Hence I started looking for the 2nd alternative i.e. Initiation from Command Prompt, so that I can create a batch file to trigger the Server. I know it's not the best practise, it's more like a workaround for not being able to start Appium Server Programmatically.

Let me know if you need any other information or clarification. I would be more than happy to respond and thank you for the wonderful work you and your team has been doing.

**Comment by imurchie** [comment]
CLI is "Command Line Interface" in this instance. It means the server that has been installed using `npm` (`npm install -g appium`) and run using `appium` from the command line.

This interface can be programmatically started (indeed, the Java client already supports easy startup and shutdown functionality).

**Comment by jlipps** [comment]
Yes, @imurchie has the answer. There are 2 ways to start Appium programmatically:

1. Run the appium CLI tool as a subprocess in your code. This means knowing how to run subprocesses in your programming language. (For example, in node.js it is `child_process.spawn`)

2. Import Appium in a Node.js application. Then you can do whatever you want with it. In fact this is how Appium Desktop interfaces with Appium. But this can only be done with Node.js.
