### ISSUE TITLE
Cannot Interact with React Native Code Input Element for Android

### ISSUE THREAD

**Issue by tpasinetti** [appium/appium-desktop#1855]
## The problem

I am automating a react native app and it uses a code input component, when interacting with this element in Appium for iOS I can input text and numbers fine, but with Android in the Appium Inspector, the react native component is converted to an Android TextView and Appium does not let me interact with this element to send keys, hence blocking me from progressing.

I have tried interacting with the element in multiple ways in my test code, but nothing is working.

Here is a screenshot of what I see in Appium inspector - Appium v. 1.19.1

<img width="1305" alt="Screen Shot 2021-06-23 at 9 14 57 am" src="https://user-images.githubusercontent.com/77592255/123011320-7eaa1c00-d403-11eb-9599-abbdc596cc19.png">

## Link to Appium logs

https://gist.github.com/tpasinetti/38318931c358e592193e5220b8b95fa9

**Comment by wswebcreation** [comment]
@tpasinetti 

The fact that you can't interact with the element might have to do with the way the components have been developed in React Native. For example, if they are created with Touchable* components, then they are accessible by default meaning their children are inaccessible. That might be the reason why you are not seeing the inputs because Appium doesn't have access to them.
The fix could be to explicitly add `accessible={false}` in all the Touchable* tags. 

Here's an example in a demo project that I use a lot. [This](All the Touchable* tags are accessible by default making the children inaccessible.
They are also the reason why all the parent tags have the same name and label.
So, my fix was to explicitly add accessible={false} in all the Touchable* tags and now I can locate individual elements without any trouble.

Touchable* = TouchableOpacity, TouchableWithoutFeedback, etc.) is a button, it has children which are normally not accessible, but by adding the `testProperties`-method with the second argument `true` the children become available. See the code of the `testProperties`-method [here](https://github.com/webdriverio/native-demo-app/blob/38c7427588c2181343f3a7919bdd8340ebb08075/src/config/TestProperties.ts#L10) 

An alternative to interact with the components without adjusting the source code is to use the keys method. Make sure that one of the elements has focus, and thus the keyboard is shown, and then send the code through the keys methods.

Hope that helps

Touchable* = TouchableOpacity, TouchableWithoutFeedback, etc.

(@mykola-mokhnach , this issue can be closed because this is not an Appium issue)

**Comment by jlipps** [comment]
thanks @wswebcreation !
