### ISSUE TITLE
Appium UI Inspector with iOS11 and xCode

### ISSUE THREAD

**Issue by freddy2** [appium/appium-desktop#308]
When will the Appium UI move from 1.6.5 to Appium 1.7.x?

With iOS 10.3.1, xCode 8 and Appium 1.6.5 ( either CLI or Desktop versions ) all worked for the most part. Our test cases passed, albeit not very reliable ever since iOS10 and Appium 1.6.x. I have no troubles with the Appium inspector in the UI version and I get same results as the often used 3rd party app-inspector tool.

I have updated to iOS11, xCode9 and appium 1.7.1. My test cases no longer pass. Many things are working, but there are a few queries that seem to not work any more. The same version product on iOS 10 and the existing setup works. -- I am suspect that our product behaves different in a few areas on the different iOS versions.

So I want to use the inspector tools to see what is different and why queries don't work. But the UI version, even the latest just updated, says its 1.6.5 and is not working. I can get a session to launch but the inspector UI is not showing anything and there is no screenshot. 

I also tried the 3rd party app-inspector tool. And this does not work either. 

At this point I am blocked on getting this working. I could use the inspector tool working with iOS 11, xCode9 and/or some other suggestions on how I can get information on the pages changes any why queries are failing.

**Comment by jlipps** [comment]
As you pointed out, Xcode 9 is only supported with Appium 1.7.1. We are working on an Appium Desktop release that bundles Appium 1.7.1. For the time being you should run Appium 1.7.1 from the command line, and simply point your new session to that instance of Appium using the "Custom Server" option.

If you run into issues that you think are regressions with 1.7.1 (regressions unrelated to changes in iOS itself, of course), please do raise them at the main Appium repo, and include all of your logs and other information.

**Comment by freddy2** [comment]
I have ran with the console version and found my test cases no long run. And why I am trying to use the desktop version and the UI inspector to see what is happening.  This does not work. 

In the end, if it takes you guys a month to get this released, then I am blocked running test cases for a month on iOS 11, as I don't have a way to examine what is wrong and fix MY queries. 

While I am waiting do you have any suggestions as to how I can make progress. 

Note the "app-inspector" console program that many often use does not work either.

**Comment by jlipps** [comment]
@freddy2 this is what I am trying to do---give you a way to run the Desktop version and UI inspector to see what is happening. Here are step-by-step instructions:

1. Start Appium 1.7.1 from the command line
2. Start the Appium Desktop app. Do NOT click "Start Server"
3. Launch the new session window (go up to "Appium desktop" (mac) or "File" (windows) and click new session from the menu)
4. Open the "Custom Server" tab of the new session window
5. Enter your local Appium server host and port (probably localhost / 4723)
6. Enter your capabilities as normal
7. Start the session as normal. This will start a session using the Appium instance you have running on the command line, which is 1.7.1.

Following these steps will enable you to inspect your app from the perspective of Appium 1.7.1.

If there are other issues, they are likely not Appium Desktop issues and should be raised at the main Appium repo where we of course want to address them. That is why I closed this issue.

In sum, the "custom server" option in the New Session window exists precisely for this reason---so that we are not blocking anyone from using _any_ Appium version they want, without having to wait on our team to bundle a version with Appium Desktop.

**Comment by freddy2** [comment]
Ah, got it. I will give this a try. Thanks!!

**Comment by deepakkg88** [comment]
@jlipps I am getting below error in appium inspector when I try to open appium inspector:

[sessionCapabilities()] Error response status: 6, Selenium error: Session does not exist
Please note that my automation code is running successfully. I am trying to launch inspector while the script is running.I am using the same session id which is automatically generated in inspector while script is running.

I am using appium 1.2.3 desktop with server 1.7.1,Xcode-9,iOS-11,IPhone 7 Plus real device.

Can you help me on this?

**Comment by mrif0393** [comment]
I cant get the tree view  inner elements appium 1.7.1,xcode 9.2,ios 10.3.2.
My code was working fine till i update my appium and xcode.Currenty it does not click the native element from the app.
I am working with web view  do some clicks and switching to native mode and clicking an element.Any help i have load the session in appium desktop version as well.No luck cant see my native elements.It shows the screen and some high level elements int he tree.Can any body help me with this.

**Comment by Venkateshg242** [comment]
@jlipps 

Can you please let us know
How to run the appium desktop from command line

**Comment by rshresthaa** [comment]
@jlipps I followed your steps but got the issue as:
Error: Could not install app: 'Command 'ios-deploy --id though I have successfully installed the command "npm install -g ios-deploy"
