### ISSUE TITLE
Appium inspector is showing the name identifier value as "AX error -25205" for all the iOS elements.

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium-desktop#314]
appium:1.7.1
appium desktop:1.7.1
xcode:9
ios real device :10.2
Mac os: 10.13

## The problem

Both the appium desktop inspector and the previous appium inspectors are showing the name identifier value as "AX error -25205"

![snip20171011_1](https://user-images.githubusercontent.com/13588038/31414353-4076b63c-ae69-11e7-9be1-bbc00114f90d.png)

**Comment by jlipps** [comment]
Unless you don't see the problem when running Appium on the command line, this is not an Appium Desktop issue. It looks instead like an Apple bug. Perhaps accessibility is not turned on on the device, or is misconfigured in the app.

**Comment by vutukuriswathi** [comment]
For the app acessiblity is working fine.I checked it by turning the voice over on iOS device

**Comment by jlipps** [comment]
I'm not sure what else I can recommend. Maybe it's not a debug build of the app? But either way it's definitely not an Appium Desktop issue. The values you see are what are being reported by XCUITest.

**Comment by vutukuriswathi** [comment]
The same app when I checked with xcode 8.2.1, it is showing the name identifier properly.So I suspect this is something u need to be fixed

**Comment by jlipps** [comment]
If you can prove that it works with Appium CLI, then I will reopen this issue. This issue tracker is for logging issues with Appium Desktop. Issues with Appium are not tracked here, they are tracked at https://github.com/appium/appium/issues.

**Comment by vutukuriswathi** [comment]
This is not a problem with the appium.This is the problem with the appium desktop.That is the reason i logged the issue here.
Here I am attaching appium desktop inspector screenshot which is working fine with xcode 8.2.1 and the same is broken on xcode9.This thing has to be fixed from appium desktop side.
Let me know if you need any further details.
![snip20171011_5](https://user-images.githubusercontent.com/13588038/31420635-73386eec-ae8e-11e7-96f6-3c635b5eab26.png)
**Appium logs to see xcode set to 8.2.1:
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/1374077/appium-server-logs.txt)
**

**Comment by jlipps** [comment]
@vutukuriswathi what I would need to reopen this issue are logs from an appium CLI server (_not_ appium desktop) showing that the issue does _not_ exist. e.g., output from the getSource command showing the accessibility labels are correct. this needs to be on xcode 9.

what you have given me instead is two screenshots from appium desktop, running on different versions of xcode. what this suggests is that the problem is xcode, not appium desktop.

to reiterate: for an issue to be tracked here it needs to be a problem with appium desktop and _not_ with appium. the way to prove that is to prove that it works with appium, under all the same conditions (same xcode version etc).

for an issue to be tracked with appium itself, it should be directed to https://github.com/appium/appium/issues.
