### ISSUE TITLE
Why the Appium Desktop can't start with server mode ? And why the Appium not update for Android 7.

### ISSUE THREAD

**Issue by learningperl** [appium/appium-desktop#512]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by sachinsankanagoudar** [comment]
i have connected IOS device and try to connecting using Appium inspector with following desired capabilities.

{
  "platformName": "IOS",
  "platformVersion": "11.3",
  "udid": "9ea7d154186a867f48n146d69e76e062076ee",
  "app": "/Users/sachi/Desktop/Mobile_apps/myapp.app",
  "noReset": true,
  "deviceName": "iPad mini",
  "xcodeOrgId": "Team ID added here",
  "xcodeSigningId": "iPhone Developer"
} 

I getting below Error message.
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

Can you please help me out here.

**Comment by dpgraham** [comment]
I'll need more details to help you with this.
