### ISSUE TITLE
Appium inspector throws error while capturing screenshot.

### ISSUE THREAD

**Issue by rakeshNew** [appium/appium-desktop#70]
Hi,

I have installed Appium Desktop Beta version "appium-desktop-Setup-1.0.0-beta.2.exe" into windows machine,  but when I click on start new session after appium server is running the Appium Inspector window opens but fails to capture the screenshot and popups the error as:

"takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: incorrect data check"

Also getting below error in Appium log 
[MJSONWP] Encountered internal error running command: Error: incorrect data check
    at Zlib._handle.onerror (zlib.js:370:17)

Please look into this issue.

Thanks,
Rakesh

**Comment by jlipps** [comment]
@rakeshNew and you've confirmed that you can successfully run a session outside of Appium Desktop, in the command-line version of Appium?

**Comment by rakeshNew** [comment]
I did not try with command-line since I installed Appium GUI version on windows machine for Andriod real devices.

**Comment by jlipps** [comment]
I see. Per the [README](https://github.com/appium/appium-desktop/blob/master/README.md), when reporting an issue here it is essential to know whether it is an issue with Appium Desktop or with Appium itself. The way to figure that out is for you to try and reproduce the issue with Appium itself. If the issue persists, then you should raise issues at https://github.com/appium/appium/issues. This issue tracker is for issues specifically related to the GUI (i.e., issues which are not present in Appium itself).

So that's the next step! See if this issue persists with the command line version of Appium.

**Comment by dpgraham** [comment]
Closing this issue for now. Please ask to re-open if the error occurs again.
