### ISSUE TITLE
simctl error running 'boot': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164): [simctl] Unable to boot device in current state: Booted

### ISSUE THREAD

**Issue by geethanjali92** [appium/appium-desktop#730]
##  Appium Desktop

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Error: simctl error running 'boot': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
[simctl] Unable to boot device in current state: Booted

## Environment

- I am running Appium Desktop version _<1.8.2>_. on Mac

please find the logs attached

[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/2598449/appium-server-logs.txt)

**Comment by dpgraham** [comment]
Can you try following these instructions: https://stackoverflow.com/questions/24135067/unable-to-boot-device-in-current-state-booted

And if it still doesn't work, bring it up with discuss.appium.io for help from the community.

And if it turns out to be a bug, can you re-open this issue in https://github.com/appium/appium/issues and provide the Appium server logs into a [gist](gist.github.com). And provide
